name: 'GitHub Actions To update content in README.md'

on: 
  push:
    paths:
      - 'content'
  pull_request:
    paths:
      - 'content'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1.2.0
      - name: install 're' python module
        run: python -m pip install re 
      - name: update README.md with content
        run: python .github/workflows/updateREADME.py
